### ISSUE TITLE
AttributeError: 'GCNConv' object has no attribute 'weight'

### ISSUE THREAD

**Issue by xulina2020** [JihoChoi/dynamic-gcn#1]
你好，运行时出现这个错误，请问这个问题怎么解决？

**Comment by JihoChoi** [comment]
`(你好，运行时出现这个错误，请问这个问题怎么解决？)`
> Google Translate: Hello, this error occurs during runtime. How to solve this problem?

Hello.

It is not clear where the error occurs, but it is expected that the version of `PyTorch Gemetric` that you are using is different from the tested version.
If an error occurred in `self.init_weights()`, I think you can simply comment the part out.
However, different dependencies may cause additional errors.

This model was tested in PyTorch 1.7 and PyTorch Geometric 1.6.
(By current standards, it is considered an old version.)

**Comment by czzhangheng** [comment]
I fixed it .
in model.py line139
use `conv1.lin.weight ` to replace `conv1.weight`
For example:
```
    def init_weights(self):  # Xavier Init
        init.xavier_normal_(self.rumor_GCN_0.TDRumorGCN.conv1.lin.weight)
        init.xavier_normal_(self.rumor_GCN_0.TDRumorGCN.conv2.lin.weight)
        init.xavier_normal_(self.rumor_GCN_0.BURumorGCN.conv1.lin.weight)
        init.xavier_normal_(self.rumor_GCN_0.BURumorGCN.conv2.lin.weight)
        init.xavier_normal_(self.W_s1.weight)
        init.xavier_normal_(self.fc.weight)
```
